export const environment1 = {
  production: false,
  realAPI: false,
  api_url: "",
  api_route: {
    SaveProgram: "SavePgmInfo",
    AreaOfResponsibility: "assets/api-data/AreaOfResponsibility.json",
    ConsolReviewResponsbility: "assets/api-data/ConsolReviewResponsbility.json",
    GetAllWFConfig: "assets/api-data/GetAllWFConfig.json",
    GetRefDataByRefTypeAllowRoles:
      "assets/api-data/GetRefDataByRefTypeAllowRoles.json",
    GetAllPgmSearchLookup: "assets/api-data/GetAllPgmSearchLookup.json",
    GetRvwTypesByPgmId: "assets/api-data/GetRvwTypesByPgmId.json",
    GetAllOffInfo: "assets/api-data/GetAllOffInfo.json",
    GetAllRvwTypes: "assets/api-data/GetAllRvwTypes.json",
    GetAssignedOffUsersByPgmId:
      "assets/api-data/GetAssignedOffUsersByPgmId.json",
    GetUnAssignedOffUsers: "assets/api-data/GetUnAssignedOffUsers.json",
    GetRefDataDocumentCategory:
      "assets/api-data/GetRefDataDocumentCategory.json",
    GetRvwDocumentNameLookup: "assets/api-data/GetRvwDocumentNameLookup.json",
    AllUsersInfo: "assets/api-data/AllUsersInfo.json",
    MyMetadata: "assets/api-data/MyMetadata.json",
    EmailTemplates: "assets/api-data/EmailTemplates.json",
    GetRefDataContactTypes: "assets/api-data/ContactType.json",
    GetRefDataFileTypesInfo: "assets/api-data/FileTypesInfo.json",
    GetAllQuestionnaireLookup: "assets/api-data/GetAllQuestionnaireLookup.json",
    GetFormMasterLookup: "assets/api-data/GetFormMasterLookup.json",
    GetFlexFormPdftemplateLookup:
      "assets/api-data/GetFlexFormPdftemplateLookup.json",
    ReviewCompliancePlanReminder: "assets/api-data/PlanRemainder.json",
  },
};
export const environment = {
  production: true,
  realAPI: true,
  api_url: "https://localhost:7057/",
  api_route: {
    SaveProgram: "SavePgmInfo",
    AreaOfResponsibility: "GetRefDataByRefType",
    ConsolReviewResponsbility: "GetRefDataByRefType",
    GetAllWFConfig: "GetAllWFConfig",
    GetRefDataByRefTypeAllowRoles: "GetRefDataByRefType",
    GetAllPgmSearchLookup: "GetAllPgmSearchLookup",
    GetRvwTypesByPgmId: "GetRvwTypesByPgmId",
    GetAllOffInfo: "GetAllOffInfo",
    GetAllRvwTypes: "GetAllRvwTypes",
    GetAssignedOffUsersByPgmId: "GetAssignedOffUsersByPgmId",
    GetUnAssignedOffUsers: "GetUnAssignedOffUsersByPgmId",
    GetRefDataDocumentCategory: "GetRefDataByRefType",
    GetRvwDocumentNameLookup: "GetDocumentNameLookup",
    AllUsersInfo: "GetAllUsersInfo",
    MyMetadata: "GetRvwTypeMetaDataByPgmId",
    EmailTemplates: "EmailTemplates",
    ReviewCompliancePlanReminder: "PlanRemainder",
    GetRefDataContactTypes: "GetRefDataByRefType",
    GetRefDataFileTypesInfo: "GetRefDataByRefType",
    GetAllQuestionnaireLookup: "GetAllQuestionnaireLookup",
    GetFormMasterLookup: "GetFormMasterLookup",
    GetFlexFormPdftemplateLookup: "GetFlexFormPdftemplateLookup",
  },
};
