export const environment = {
  production: true,
  realAPI: true,
  api_url: "https://localhost:7057/",
  api_route: {
    SaveProgram: "SavePgmInfo",
    GetReviewResponsibility: "GetRefDataByRefType",
    GetAllWFConfig: "GetAllWFConfig",
    GetRefDataByRefTypeAllowRoles: "GetRefDataByRefType",
    GetAllPgmSearchLookup: "GetAllPgmSearchLookup",
    GetRvwTypesByPgmId: "GetRvwTypesByPgmId",
    GetAllOffInfo: "GetAllOffInfo",
    GetAllRvwTypes: "GetAllRvwTypes",
    GetAssignedOffUsersByPgmId: "GetAssignedOffUsersByPgmId",
    GetUnAssignedOffUsers: "GetUnAssignedOffUsersByPgmId",
    GetRefDataByRefType: "GetRefDataByRefType",
    GetRvwDocumentNameLookup: "GetRvwDocumentNameLookup",
    AllUsersInfo: "AllUsersInfo",
    MyMetadata: "MyMetadata",
    EmailTemplates: "EmailTemplates",
  },
};
